project:
  type: book
  output-dir: _site
execute: 
  freeze: auto
  echo: false
  warning: false
book:
  title: "Data Analysis and Visualization for Chemists and Material Scientists"
  subtitle: "A Practical Guide with Python"
  author: "© 2025 Stefanie Kröll"
  version: 0.1
  page-navigation: true
  reader-mode: true
  open-graph: true
  page-footer:
    right: | 
      <li><a href="https://github.com/stkroe/PythonForChemists.github.io" target="blank">Code source</a></li>
    center: |
      © 2025 Stefanie Kröll. All rights reserved.
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/stkroe/PythonForChemists.github.io
  repo-actions: [edit,issue]
  repo-branch: master

  sidebar:
    style: "docked"
    search: true
    logo: logo.png

  chapters:
      - index.qmd
      - part: "Introduction"
        chapters:
          - course/chapters/Introduction/ToolsOfDataScience.ipynb
          - course/chapters/Introduction/WhatIsPython.ipynb
          - course/chapters/Introduction/InstallationGuide.ipynb
      - part: "Python Basics"
        chapters:
          - course/chapters/Basics/Basics.ipynb
          - course/chapters/Basics/BasicsModules.ipynb
     
bibliography: references.bib

format:
  html:
    light: lumen
    dark:  darkly
    code-link: true
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    code-fold: false
    fig-cap: true
    self-contained: true
    number-sections: false
 