project:
  type: book
  output-dir: _site
execute: 
  freeze: auto
  echo: false
  warning: false
book:
  title: "Data Analysis and Visualization for Chemists and Material Scientists"
  subtitle: "A Practical Guide with Python"
  author: "© 2025 Stefanie Kröll"
  version: 0.1
  page-navigation: true
  reader-mode: true
  open-graph: true
  page-footer:
    right: | 
      <li><a href="https://github.com/stkroe/PythonForChemists.github.io" target="blank">Code source</a></li>
    center: |
      © 2025 Stefanie Kröll. All rights reserved.
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/stkroe/PythonForChemists.github.io
  repo-actions: [edit,issue]
  repo-branch: master

  sidebar:
    style: "docked"
    search: true
    logo: logo.png

  chapters:
      - index.qmd
      - part: "Essentials"
        chapters:
          - course/chapters/Introduction/Lecture0/Introduction.qmd
          - course/chapters/Introduction/Lecture0/WhatIsPython.qmd
          - course/chapters/Introduction/Lecture0/InstallationGuide.qmd
      - part: "Python Crash Course"
        chapters:
          - course/chapters/Python/Basics.qmd
          - course/chapters/Python/BasicsModules.qmd
      - part: "Lecture 1"
        chapters:
          - course/chapters/Introduction/Lecture1/DataCollection.qmd
          - course/chapters/Basics/Lecture1/SimpleDataImport.qmd
          - course/chapters/Basics/Lecture1/SimpleDataInspection.qmd
          - course/chapters/Basics/Lecture1/SimplePlot.qmd
          - course/chapters/exercises/exercises/exercise1.ipynb
          # - course/chapters/Intermediate/Lecture1/SpecialDataImport.ipynb
          # - course/chapters/Advanced/Lecture1/AdvancedDataImport.ipynb
      # - part: "Lecture 2"
      #   chapters:
      #     - course/chapters/Introduction/Lecture2/Introduction.ipynb
      #     - course/chapters/Basics/Lecture2/BasicDataAnalysis.ipynb
      #     - course/chapters/Intermediate/Lecture2/IntermediateDataAnalysis.ipynb
      #     - course/chapters/Advanced/Lecture2/AdvancedDataAnalysis.ipynb
      - part: "Informations"
        chapters:
         - informations/references.qmd
         - informations/license.qmd
         - informations/privacy.qmd
         - informations/impressum.qmd
         - informations/disclaimer.qmd
bibliography: references.bib

format:
  live-html: 
      theme: "book"
      highlight-style: "github"
      code-copy: true
      code-overflow: wrap
      toc: true
      toc-depth: 3
      code-fold: false
      fig-cap: true
      #self-contained: true
      number-sections: false
      #embed-resources: true
      link-external-icon: true
      link-external-newwindow: true
colab:
  gh-user: "stkroe"    # Your GitHub username
  gh-repo: "PythonforChemists"    # Your repository name
  gh-branch: "gh-pages"      # Optional, defaults to "main"
filters:
  - colab