project:
  type: book
  output-dir: _site
execute: 
  freeze: auto
  echo: false
  warning: false
book:
  title: "Data Analysis and Visualization for Chemists and Material Scientists"
  subtitle: "A Practical Guide with Python"
  author: "© 2025 Stefanie Kröll"
  version: 0.1
  page-navigation: true
  reader-mode: true
  open-graph: true
  page-footer:
    right: | 
      <li><a href="https://github.com/stkroe/PythonForChemists.github.io" target="blank">Code source</a></li>
    center: |
      © 2025 Stefanie Kröll. All rights reserved.
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/stkroe/PythonForChemists.github.io
  repo-actions: [edit,issue]
  repo-branch: master

  sidebar:
    style: "docked"
    search: true
    logo: logo.png

  chapters:
      - index.qmd
      - part: "Essentials"
        chapters:
          - course/chapters/Essentials/Introduction.qmd
          - course/chapters/Essentials/WhatIsPython.qmd
          - course/chapters/Essentials/InstallationGuide.qmd
          - course/chapters/Essentials/Editors.qmd
      - part: "Python Crash Course"
        chapters:
          - course/chapters/Python/Basics.qmd
          - course/chapters/Python/Intermediate.qmd
          - course/chapters/Python/BasicsModules.qmd
          - course/chapters/Python/AdvancedModules.qmd
      - part: "Data Handling and Preprocessing"
        chapters:
          - course/chapters/DHP/DataCollection.qmd
          - course/chapters/DHP/SimpleDataImport.qmd
          - course/chapters/DHP/SimpleDataInspection.qmd
         
      - part: "Simple Plotting"
        chapters:
          - course/chapters/Plots/DataVisualization.qmd
          - course/chapters/Plots/SimplePlots.qmd
          - course/exercises/exercises/exercise1.ipynb
      - part: "Statistical and Exploratory Data Analysis"
        chapters:
          - course/chapters/SEDA/SimpleDataManipulation.qmd
          - course/chapters/SEDA/SimpleDataModels.qmd
          - course/chapters/SEDA/ModelTesting.qmd
      - part: "Spectroscopy and Image Data"
        chapters:
          - course/chapters/SID/Spectroscopy.qmd
          - course/chapters/SID/ImageAnalysis.qmd
      # - part: "Machine Learning"
      #   chapters:
      #     - course/chapters/ML/IntroductionML.qmd
      #     - course/chapters/ML/MLBasics.qmd
      #     - course/chapters/ML/MLModels.qmd
      #     - course/chapters/ML/MLValidation.qmd
      #     - course/chapters/ML/MLDeployment.qmd
      - part: "Informations"
        chapters:
         - informations/references.qmd
         - informations/license.qmd
         - informations/privacy.qmd
         - informations/impressum.qmd
         - informations/disclaimer.qmd
bibliography: references.bib

format:
  html: 
      theme: 
        light: [cosmo]  # Light theme
        dark: [darkly]   # Dark theme
      #highlight-style: "tango"
      code-copy: true
      code-overflow: wrap
      toc: true
      toc-depth: 3
      code-fold: false
      fig-cap: true
      #self-contained: true
      number-sections: false
      #embed-resources: true
      link-external-icon: true
      link-external-newwindow: true
colab:
  gh-user: "stkroe"    # Your GitHub username
  gh-repo: "PythonforChemists"    # Your repository name
  gh-branch: "gh-pages"      # Optional, defaults to "main"
filters:
  - colab