name: otter-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - nb_conda_kernels
  - jupyter_server
  - pip:
      - otter-grader[grading,plugins]==6.1.2
      - pandas
      - numpy
      - matplotlib
      - jupyter
      - jupyterlab
      - scikit-learn
      - scipy
      - seaborn
      - statsmodels
      - otter-grader[grading,plugins,r]==6.1.2
      - umap-learn
      - bokeh
      - altair
      - plotly
      - networkx
      - python-ternary
