---
title: "Installation Guide"
execute:
    echo: false
    eval: false
    collaps: false
---
Difficulty level: <span style="color:#2B7492">{{< bi star >}} </span>

Here is a short instruction how to install Python on your local PC or you can use [Google Colab](https://colab.research.google.com) to solve all the exercises of this course.

:::{.callout-information}
The use of [Google Colab](https://colab.research.google.com) needs a Google Account. Please read the [Terms of Service](https://research.google.com/colaboratory/tos_v5.html) and [Privacy Policy](https://policies.google.com/privacy)
:::


# How to install Python locally? {.unnumbered}


Fundamental Python websites:

- [Python](https://www.python.org) 
- [Python documentation](https://www.python.org/doc/)


## 1. Install Python Interpreter (you do not needed if you use an environment manager) {.unnumbered} 


Your preferred searching engine is your friend to find the best way to install Python on your system.
Please choose that method which is suitable for you.


Python can be installed by several ways:



- directly by [Python](https://www.python.org/downloads/) official site 
    - the installation guide can be found under [python wiki](https://wiki.python.org/moin/BeginnersGuide/Download)
- or via package manager of your os: 
    - *e.g.:* `sudo apt install python` (linux debian) or `brew install python` (macOS)
- or via [docker](https://www.docker.com/), [wsl](https://learn.microsoft.com/de-de/windows/wsl/install) ect.
- or via a [conda](https://docs.conda.io/projects/conda/en/latest/index.html) or [mamba](https://mamba.readthedocs.io/en/latest/index.html) python package and environment managers which have a python interpreter on board and are available for Windows, Linux and macOS [my recommendation]



## 2. Python Package and Environment manager {.unnumbered}


The advantage of using a python package and environment manager is that you have a python interpreter directly on board, but you can also directly create different python enviroments and install and remove python packages.


### Conda {.unnumbered}


There are differerent `conda` installer:
(Please pay attention which one is suitable for you ([https://docs.anaconda.com/distro-or-miniconda/](https://docs.anaconda.com/distro-or-miniconda/)).

:::{.callout-warning}
Please read the [Anaconda Terms of Service FAQs](https://www.anaconda.com/pricing/terms-of-service-faqs) and [Terms of Service](https://legal.anaconda.com/policies/en/)) **not** every case is **free** of charge of use. 

:::


- [Anaconda Distribution](https://docs.anaconda.com/anaconda/install/) is a comprehensive distribution which includes conda and hundreds of preinstalled packages and tools.
- [miniconda](https://docs.anaconda.com/free/miniconda/index.html) is the light version of it which contains only conda, python interpreter and few fundamental packages
- [miniforge](https://github.com/conda-forge/miniforge) minimal installer for conda and using only the community [conda-forge](https://conda-forge.org/) channel



### Mamba {.unnumbered}


Another python package and environment manager is [mamba](https://mamba.readthedocs.io/en/latest/index.html).

`mamba` is a reimplementation of `conda`:

 - [micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) is a statically linked version of `mamba` 
 - `mamba`and it is currently faster than `conda`


:::{.callout-tip}
 **Recommendation: *micromamba* ** <br>

Install it like it is explained under the micromamba documentation:
- [https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html)
:::


Please install in one of the above explained ways Python and use your preferred searching engine to get more information.


## 3. Set up an environment {.unnumbered}

It is often very useful to have different python environments for different python projects because of the need of different python package versions.

You can use `conda` or `micromamba` to create different environments. There exists also other virtual environment manager.

In this course the explanation is restricted to `micromamba` as an example. If you want to use something else there exists tons of information online how to use other programs.




### Micromamba: Most important commands are: {.unnumbered}


Read for more detail: [https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html)



Creating a new virtual environment:


```bash
micromamba create --name <myenvname>
```


Install new packages:


```bash
micromamba install <packagename>
```


List all environments:


```bash
micromamba env list
```


Activate an environment:


```bash
micromamba activate <myenvname>
```


List all packages of this environment:


```bash
micromamba list
```


## 4. Usefull packages for Data Analysis and Visualization:  {.unnumbered}
- [pip](https://packaging.python.org/en/latest/guides/tool-recommendations/) - package installer for python instead of conda
- [jupyter-notebook/jupyterlab](https://jupyter.org/) - interactive computing environment
- [ipykernel](https://pypi.org/project/ipykernel/) - IPython Kernel for Jupyter
- [matplotlib](https://matplotlib.org) - data visualization library
- [numpy](https://numpy.org) - numerical library
- [scipy](https://docs.scipy.org/doc/scipy/reference/) - scientific library
- [pandas](https://pandas.pydata.org/docs/) - data manipulation library
- [seaborn](https://seaborn.pydata.org/examples/index.html) - data visualization library
- [scikit-learn](https://scikit-learn.org/stable/) - machine learning library
- [statsmodels](https://www.statsmodels.org/stable/index.html) - statistical library

**special packages for data visualization:**

- [bokeh](https://docs.bokeh.org/en/latest/index.html) - interactive data visualization library
- [plotly](https://plotly.com/python/) - interactive data visualization library
- [networkx](https://networkx.org/documentation/stable/) - network analysis library
- [python-ternary](https://python-ternary.readthedocs.io/en/latest/) - ternary plot library
- [altair](https://altair-viz.github.io/) - declarative statistical visualization library
- [umap-learn](https://umap-learn.readthedocs.io/en/latest/) - dimensionality reduction library

**special packages for chemistry and material science:**

- [ase](https://wiki.fysik.dtu.dk/ase/) - atomic simulation environment
- [pymatgen](https://pymatgen.org/) - Python Materials Genomics
- [RdKit](https://www.rdkit.org/docs/index.html) - cheminformatics library
- [openbabel](https://openbabel.org/index.html) - cheminformatics library
- [pymol-opensource](https://pymol.org/#opensource) - molecular visualization library

For more chemistry and material science packages please check the [Awesome Python Chemistry](https://github.com/lmmentel/awesome-python-chemistry) repository.



## Short Cut {.unnumbered}
:::{.callout-tip}
**Recommendation** <br> 
Use *yml-file* with all needed packages and configurations:
:::


Save your needed packages in an `environment.yml` file *e.g.*:


 ```{yml}
 name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
 ```


and create an environment with this specific packages:


```bash
micromamba env create -f environment.yml
```

Then you can activate it via:
```bash
micromamba activate myenv
```
## 5. Test your installation {.unnumbered}

Test your installation by opening the interactive python mode by typing in your terminal (Linux, macOS) / command prompt (Windows):



```bash
python
``` 


then something like this should be opened in your terminal (Linux, macOS) / command prompt (Windows)

```bash
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```


then type:


```python
print("Hello World!")
```

If this works your installation was successful!